[workspace]
resolver = "2"

members = [
    "crates/*",
]

# Dependencies that should be kept in sync through the whole workspace
[workspace.dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.83"
arbitrary = { version = "1.3.2", features = ["derive", "derive_arbitrary"] }
async-trait = "0.1.80"
bcs = "0.1.6"
better_any = { version = "0.2.0", features = ["derive"] }
bitvec = "1.0.1"
byteorder = "1.5.0"
bytes = "1.6.0"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
codespan = "0.11.1"
codespan-reporting = "0.11.1"
colored = "2.1.0"
criterion = "0.3.4"
criterion-cpu-time = "0.1.0"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.12"
crossterm = "0.27.0"
curve25519-dalek = { version = "0.1.0", package = "curve25519-dalek-fiat", default-features = false, features = ["std", "u64_backend"] }
datatest-stable = "0.2.9"
derivative = "2.2.0"
difference = "2.0.0"
digest = "0.10.7"
dir-diff = "0.3.3"
dirs-next = "2.0.0"
dunce = "1.0.4"
ed25519-dalek = { version = "0.1.0", package = "ed25519-dalek-fiat", default-features = false, features = ["std", "serde", "u64_backend"] }
ethnum = "1.5.0"
fail = "0.5.1"
file_diff = "1.0.0"
futures = "0.3.30"
getrandom = "0.2.15"
heck = "0.5.0"
hex = "0.4.3"
hex-literal = "0.4.1"
hkdf = "0.12.4"
im = "15.1.0"
internment = { version = "0.8.3", features = [ "arc"] }
itertools = "0.13.0"
leb128 = "0.2.5"
libfuzzer-sys = "0.4.7"
log = { version = "0.4.21", features = ["serde"] }
lsp-server = "0.7.6"
lsp-types = "0.97.0"
memory-stats = "1.1.0"
mirai-annotations = "1.12.0"
named-lock = "0.4.1"
num = "0.4.3"
num-bigint = "0.4.5"
num_cpus = "1.16.0"
once_cell = "1.19.0"
ouroboros = "0.18.3"
parking_lot = "0.12.2"
paste = "1.0.15"
pathdiff = "0.2.1"
petgraph = "0.6.5"
phf = { version = "0.11.2", features = ["macros"] }
plotters = { version = "0.3.5", default_features = false, features = ["evcxr", "line_series", "histogram"]}
pretty = "0.12.3"
prettydiff = "0.7.0"
primitive-types = { version = "0.12.2", features = ["impl-serde"]}
proc-macro2 = "1.0.82"
proptest = "1.4.0"
proptest-derive = "0.4.0"
quote = "1.0.36"
rand = "0.8.5"
rayon = "1.10.0"
ref-cast = "1.0.23"
regex = "1.10.4"
ripemd160 = "0.10.0"
serde = { version = "1.0.202", features = ["derive"] }
serde-name = "0.2.1"
serde-reflection = "0.4.0"
serde_bytes = "0.11.14"
serde_json = "1.0.117"
serde_yml = "0.0.10"
sha2 = "0.10.8"
sha3 = "0.10.8"
shell-words = "1.1.0"
simplelog = "0.12.2"
similar = "2.5.0"
smallvec = "1.13.2"
stacker = "0.1.15"
static_assertions = "1.1.0"
syn = "2.0.63"
tempfile = "3.10.1"
tera = "1.19.1"
thiserror = "1.0.60"
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.12"
toml_edit =  "0.22.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
treeline = "0.1.0"
tui = "0.19.0"
uint = "0.9.5"
url = "2.5.0"
variant_count = "1.1.0"
vfs = "0.12.0"
walkdir = "2.5.0"
whoami = { version = "1.5.1" }
x25519-dalek = { version = "0.1.0", package = "x25519-dalek-fiat", default-features = false, features = ["std", "u64_backend"] }
z3tracer = "0.11.2"

bytecode-interpreter-crypto = { path = "crates/bytecode-interpreter-crypto" }
enum-compat-util = { path = "crates/enum-compat-util"}
invalid-mutations = { path = "crates/invalid-mutations" }
module-generation = { path = "crates/module-generation" }
move-abstract-stack = { path = "crates/move-abstract-stack" }
move-binary-format = { path = "crates/move-binary-format" }
move-borrow-graph = { path = "crates/move-borrow-graph" }
move-bytecode-source-map = { path = "crates/move-bytecode-source-map" }
move-bytecode-utils = { path = "crates/move-bytecode-utils" }
move-bytecode-verifier = { path = "crates/move-bytecode-verifier" }
move-bytecode-viewer = { path = "crates/move-bytecode-viewer" }
move-cli = { path = "crates/move-cli" }
move-command-line-common = { path = "crates/move-command-line-common" }
move-compiler = { path = "crates/move-compiler" }
move-core-types = { path = "crates/move-core-types" }
move-coverage = { path = "crates/move-coverage" }
move-disassembler = { path = "crates/move-disassembler" }
move-docgen = { path = "crates/move-docgen" }
move-errmapgen = { path = "crates/move-errmapgen" }
move-ir-compiler = { path = "crates/move-ir-compiler" }
move-ir-to-bytecode = { path = "crates/move-ir-to-bytecode" }
move-ir-to-bytecode-syntax = { path = "crates/move-ir-to-bytecode-syntax" }
move-ir-types = { path = "crates/move-ir-types" }
move-model = { path = "crates/move-model" }
move-package = { path = "crates/move-package" }
move-proc-macros = { path = "crates/move-proc-macros"}
move-prover = { path = "crates/move-prover" }
move-prover-test-utils = { path = "crates/move-prover-test-utils" }
move-read-write-set-types = { path = "crates/move-read-write-set-types" }
move-stackless-bytecode = { path = "crates/move-stackless-bytecode" }
move-stackless-bytecode-interpreter = { path = "crates/move-stackless-bytecode-interpreter" }
move-stdlib = { path = "crates/move-stdlib" }
move-symbol-pool = { path = "crates/move-symbol-pool" }
move-transactional-test-runner = { path = "crates/move-transactional-test-runner" }
move-unit-test = { path = "crates/move-unit-test" }
move-vm-config = { path = "crates/move-vm-config" }
move-vm-profiler = { path = "crates/move-vm-profiler" }
move-vm-runtime = { path = "crates/move-vm-runtime" }
move-vm-test-utils = { path = "crates/move-vm-test-utils" }
move-vm-types = { path = "crates/move-vm-types" }
prover_bytecode = { path = "crates/move-stackless-bytecode", package="move-stackless-bytecode" }

[profile.bench]
debug = true

[profile.dev]
debug = true

[profile.test.package.move-vm-integration-tests]
# opt-level 2 for move-compiler reduces the size of some of its
# (recursive) stack frames by up to 10x, avoiding stack overflows.
opt-level = 3

# use release settings to reduce memory pressure in the linking step in CI
[profile.ci]
inherits = "test"
debug = 0 # for saving disk space during linking
incremental = false
codegen-units = 16
