[package]
name = "iota-simulator"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
move-package.workspace = true

anemo.workspace = true
anemo-tower.workspace = true
bcs.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
iota-framework.workspace = true
iota-move-build.workspace = true
iota-types.workspace = true
lru.workspace = true
narwhal-network.workspace = true
rand.workspace = true
serde.workspace = true
telemetry-subscribers.workspace = true
tempfile.workspace = true
tower.workspace = true
tracing.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
tokio.workspace = true
real_tokio = { git = "https://github.com/mystenmark/tokio-madsim-fork.git", rev = "e47aafebf98e9c1734a8848a1876d5946c44bdd1", features = ["full"] }
