[package]
name = "$PACKAGE_NAME"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../../../../../sui-framework/packages/move-stdlib" }
Sui = { local = "../../../../../sui-framework/packages/sui-framework" }
Stardust = { local = "../../../../../sui-framework/packages/stardust" }

[addresses]
alias = "$ALIAS"