[package]
name = "publish_tx"
authors = ["IOTA Stiftung"]
edition = "2021"
license = "Apache-2.0"
publish = false



[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
bcs = "0.1.4"
bip32 = "0.5.1"
tokio = "1.38.0"
serde_json = "1.0.64"

iota-keys = { path = "../../../../iota-keys" }
iota-sdk = { path = "../../../../iota-sdk" }
shared-crypto = { path = "../../../../shared-crypto" }
move-core-types = { path = "../../../../../external-crates/move/crates/move-core-types" }
iota-move-build = { path = "../../../../iota-move-build" }
iota-replay = { path = "../../../"}
[workspace]
