[package]
name = "iota-common"
authors = ["IOTA Foundation <contact@iota.org>"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio.workspace = true
futures.workspace = true
parking_lot.workspace = true
