[package]
name = "iota-graphql-config"
version.workspace = true
authors = ["IOTA Foundation <build@iota.org"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
