[package]
name = "Tutorial"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../crates/iota-framework/packages/move-stdlib/" }
IOTA = { local = "../../../crates/iota-framework//packages/iota-framework" }

[addresses]
tutorial = "0x0"
