[alias]
# Configuration specifically for running clippy on `external-crates/move/`.
# Some of these allows are to avoid code churn; others are filed as issues on the `sui` repo now.
move-clippy = [
  "clippy",
  "--manifest-path external-crates/move/Cargo.toml",
  "--",
  "-Wclippy::all",
  "-Wclippy::disallowed_methods",
  "-Aclippy::upper_case_acronyms",
  "-Aclippy::type_complexity",
  # Remove after https://github.com/rust-lang/rust-clippy/pull/11792 is released.
  "-Aclippy::map_identity",
  "-Aclippy::new_without_default",
  "-Aclippy::box_default",
  "-Aclippy::manual_slice_size_calculation",
]

ci-clippy = "clippy --all-targets --all-features -- -D warnings"
ci-license = "license-template --template .license_template"

[build]
rustflags = ["-C", "force-frame-pointers=yes", "-C", "force-unwind-tables=yes"]

# 64 bit MSVC, override default 1M stack with 8M stack
[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C",
  "link-arg=/STACK:8000000",
]
