[package]
name = "TimeLock"
version = "0.0.1"
published-at = "0x10cf"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
IOTA = { local = "../iota-framework" }
IOTASystem = { local = "../iota-system" }

[addresses]
timelock = "0x10cf"
