[package]
name = "demo"
version = "0.0.1"

[dependencies]
IOTA = { git = "https://github.com/iotaledger/kinesis.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }

[addresses]
demo = "0x0"
