[package]
name = "Locked Stake"
version = "0.0.1"

[dependencies]
IOTA = { local = "../../../crates/iota-framework/packages/iota-framework" }
IOTASystem = { local = "../../../crates/iota-framework/packages/iota-system" }

[addresses]
locked_stake = "0x0"
