[package]
name = "shared-with-tto"
version = "0.0.1"

[dependencies]
IOTA = { git = "https://github.com/iotaledger/kinesis.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/devnet" }
common = { local = "../common" }

[addresses]
shared_with_tto = "0x0"
