global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
      - targets: ["host.docker.internal:9184"]
